### ISSUE TITLE
GHC 8.8 Updates

### ISSUE THREAD

**Issue by lancelet** [diagrams/diagrams-travis#9]
Some builds using these scripts with ghc-8.8 seem to be failing. Example:
https://travis-ci.org/diagrams/active/jobs/592641319#L363

**Comment by byorgey** [comment]
Hopefully this is fixed by #10 ?  I tried restarting the linked `active` build, we'll see how it goes.

**Comment by lancelet** [comment]
`active` seems to be compiling happily. I'll close.
